### PR TITLE
Add optional next year and previous year options for calendar navigation

### PR DESCRIPTION
**Pull request by alexbirtwell**
Started using this plugin and think it's great. I'm hoping to use it for part of a booking management system and noticed for my use case it would be good to have a next and previous year option which wasn't available without Forking your repo. Always good to give back to great projects so hopefully its something you can include.

### CODE REVIEW

**Comment by mikrosmile** [comment]
Thanks for your contribution. 
Im going to make dropdown where you can choose year / month. 
Is it better or stick with your solution?

**Comment by alexbirtwell** [comment]
> 

As it's optional I'd say include both. My next plan was to look at change the month text in the middle of the navigation to a drop down and add a year to

**Review by mikrosmile — APPROVED** [review]

**Review by mikrosmile — APPROVED** [review]

**Review by mikrosmile — APPROVED** [review]

**Comment by mikrosmile** [comment]
I'll close this PR as it had some errors in code and refactored some styling. Next time, please consider, that users already published config and if we add something new, it would give an error, so we have to add default states for that options. But on next release i'll add it to core. Thanks

**Comment by mikrosmile** [comment]
Implemented in latest release.
Thanks.

**Pull request closed without merging**
